In [ ]:

# IMPORT LIBRARIES

import pandas as pd
import numpy as np

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    cross_val_score
)

from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler
)

from sklearn.impute import SimpleImputer

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

In [ ]:
# CLASSIFICATION PROBLEM 1-dataset1
# Can qualification relevance be predicted?

print("\n===================================")
print("CLASSIFICATION PROBLEM 1")
print("===================================")

# SELECT FEATURES AND TARGET

X1 = df1[[
    'employment_status',
    'sex',
    'age_group',
    'age_midpoint',
    'number_of_non_school_qualifications',
    'qualification_recency',
    'current_job_skill_level',
    'country_of_birth_group',
    'citizenship_status',
    'occupation',
    'occupation_earners_2022_23',
    'occupation_median_age_2022_23',
    'occupation_sum_income_2022_23',
    'occupation_median_income_2022_23',
    'occupation_mean_income_2022_23',
    'occupation_income_level',
    'occupation_income_rank'
]]



CLASSIFICATION PROBLEM 1


In [ ]:
# LOAD DATASETS

# DATASET 1
df1 = pd.read_csv("rq1_qualification_relevance_part1_dataset_v2.csv")

# DATASET 2
df2 = pd.read_csv("rq2_migrant_income_part1_dataset_v2.csv")


In [ ]:
y1 = df1['target']

# HANDLE MISSING VALUES

cat_cols1 = X1.select_dtypes(include='object').columns
num_cols1 = X1.select_dtypes(exclude='object').columns

cat_imputer = SimpleImputer(strategy='most_frequent')
num_imputer = SimpleImputer(strategy='median')

X1[cat_cols1] = cat_imputer.fit_transform(X1[cat_cols1])
X1[num_cols1] = num_imputer.fit_transform(X1[num_cols1])

In [ ]:
# LABEL ENCODING


for col in cat_cols1:
    le = LabelEncoder()
    X1[col] = le.fit_transform(X1[col])

target_encoder1 = LabelEncoder()
y1 = target_encoder1.fit_transform(y1)

In [ ]:
# TRAIN TEST SPLIT

X1_train, X1_test, y1_train, y1_test = train_test_split(
    X1,
    y1,
    test_size=0.2,
    random_state=42,
    stratify=y1
)


In [ ]:
# FEATURE SCALING

scaler1 = StandardScaler()

X1_train_scaled = scaler1.fit_transform(X1_train)
X1_test_scaled = scaler1.transform(X1_test)

In [ ]:
# MODEL 1 - RANDOM FOREST

print("\n----- RANDOM FOREST -----")

rf = RandomForestClassifier(random_state=42)

param_grid_rf = {
    'n_estimators': [100, 200],
    'max_depth': [5, 10, None]
}

grid_rf = GridSearchCV(
    rf,
    param_grid_rf,
    cv=5,
    scoring='f1_weighted'
)

grid_rf.fit(X1_train, y1_train)

best_rf = grid_rf.best_estimator_

y_pred_rf = best_rf.predict(X1_test)

print("Best Parameters:", grid_rf.best_params_)

print("Accuracy:",
      accuracy_score(y1_test, y_pred_rf))

print("Precision:",
      precision_score(y1_test, y_pred_rf,
                      average='weighted'))

print("Recall:",
      recall_score(y1_test, y_pred_rf,
                   average='weighted'))

print("F1 Score:",
      f1_score(y1_test, y_pred_rf,
               average='weighted'))

print("\nClassification Report")
print(classification_report(y1_test, y_pred_rf))

print("\nConfusion Matrix")
print(confusion_matrix(y1_test, y_pred_rf))


----- RANDOM FOREST -----
Best Parameters: {'max_depth': 10, 'n_estimators': 200}
Accuracy: 0.8452261306532663
Precision: 0.8260144972145395
Recall: 0.8452261306532663
F1 Score: 0.8311606717187329

Classification Report
              precision    recall  f1-score   support

           0       0.56      0.36      0.44       332
           1       0.88      0.94      0.91      1658

    accuracy                           0.85      1990
   macro avg       0.72      0.65      0.67      1990
weighted avg       0.83      0.85      0.83      1990


Confusion Matrix
[[ 119  213]
 [  95 1563]]


In [ ]:
# CROSS VALIDATION

rf_cv = cross_val_score(
    best_rf,
    X1,
    y1,
    cv=5,
    scoring='accuracy'
)

print("\nCross Validation Accuracy:",
      rf_cv.mean())



Cross Validation Accuracy: 0.7446104327570483


In [ ]:
# MODEL 2 - SUPPORT VECTOR MACHINE

print("\n----- SUPPORT VECTOR MACHINE -----")

svm = SVC(
    kernel='rbf',
    probability=True,
    random_state=42
)

param_grid_svm = {
    'C': [0.1, 1],
    'gamma': ['scale', 0.1]
}

grid_svm = GridSearchCV(
    svm,
    param_grid_svm,
    cv=5,
    scoring='f1_weighted'
)

grid_svm.fit(X1_train_scaled, y1_train)

best_svm = grid_svm.best_estimator_

y_pred_svm = best_svm.predict(X1_test_scaled)

print("Best Parameters:", grid_svm.best_params_)

print("Accuracy:",
      accuracy_score(y1_test, y_pred_svm))

print("Precision:",
      precision_score(y1_test, y_pred_svm,
                      average='weighted'))

print("Recall:",
      recall_score(y1_test, y_pred_svm,
                   average='weighted'))

print("F1 Score:",
      f1_score(y1_test, y_pred_svm,
               average='weighted'))

print("\nClassification Report")
print(classification_report(y1_test, y_pred_svm))

print("\nConfusion Matrix")
print(confusion_matrix(y1_test, y_pred_svm))



----- SUPPORT VECTOR MACHINE -----
Best Parameters: {'C': 1, 'gamma': 0.1}
Accuracy: 0.8507537688442212
Precision: 0.8281228568974619
Recall: 0.8507537688442212
F1 Score: 0.8285297591932634

Classification Report
              precision    recall  f1-score   support

           0       0.61      0.30      0.40       332
           1       0.87      0.96      0.91      1658

    accuracy                           0.85      1990
   macro avg       0.74      0.63      0.66      1990
weighted avg       0.83      0.85      0.83      1990


Confusion Matrix
[[  98  234]
 [  63 1595]]


In [ ]:
# CROSS VALIDATION

svm_cv = cross_val_score(
    best_svm,
    scaler1.fit_transform(X1),
    y1,
    cv=5,
    scoring='accuracy'
)

print("\nCross Validation Accuracy:",
      svm_cv.mean())



Cross Validation Accuracy: 0.7222884659597637


In [ ]:
# CLASSIFICATION PROBLEM 2-Dataset 2
# Can migrant employee income group be predicted?

print("\n===================================")
print("CLASSIFICATION PROBLEM 2")
print("===================================")

# SELECT FEATURES AND TARGET

X2 = df2[[
    'visa_group',
    'age_range',
    'applicant_status',
    'sex',
    'arrival_group',
    'age_midpoint'
]]

y2 = df2['income_target']

# HANDLE MISSING VALUES

cat_cols2 = X2.select_dtypes(include='object').columns
num_cols2 = X2.select_dtypes(exclude='object').columns

X2[cat_cols2] = cat_imputer.fit_transform(X2[cat_cols2])
X2[num_cols2] = num_imputer.fit_transform(X2[num_cols2])

# LABEL ENCODING

for col in cat_cols2:
    le = LabelEncoder()
    X2[col] = le.fit_transform(X2[col])

target_encoder2 = LabelEncoder()
y2 = target_encoder2.fit_transform(y2)

# TRAIN TEST SPLIT

X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2,
    y2,
    test_size=0.2,
    random_state=42,
    stratify=y2
)

# FEATURE SCALING

scaler2 = StandardScaler()

X2_train_scaled = scaler2.fit_transform(X2_train)
X2_test_scaled = scaler2.transform(X2_test)



CLASSIFICATION PROBLEM 2


C:\Users\Admin\AppData\Local\Temp\ipykernel_20512\3871026828.py:32: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X2[cat_cols2] = cat_imputer.fit_transform(X2[cat_cols2])
C:\Users\Admin\AppData\Local\Temp\ipykernel_20512\3871026828.py:33: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X2[num_cols2] = num_imputer.fit_transform(X2[num_cols2])
C:\Users\Admin\AppData\Local\Temp\ipykernel_20512\3871026828.py:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using 

In [ ]:
# MODEL 1 - DECISION TREE

print("\n----- DECISION TREE -----")

dt = DecisionTreeClassifier(random_state=42)

param_grid_dt = {
    'max_depth': [3, 5, 10],
    'min_samples_split': [2, 5]
}

grid_dt = GridSearchCV(
    dt,
    param_grid_dt,
    cv=5,
    scoring='f1'
)

grid_dt.fit(X2_train, y2_train)

best_dt = grid_dt.best_estimator_

y_pred_dt = best_dt.predict(X2_test)

print("Best Parameters:", grid_dt.best_params_)

print("Accuracy:",
      accuracy_score(y2_test, y_pred_dt))

print("Precision:",
      precision_score(y2_test, y_pred_dt))

print("Recall:",
      recall_score(y2_test, y_pred_dt))

print("F1 Score:",
      f1_score(y2_test, y_pred_dt))

print("\nClassification Report")
print(classification_report(y2_test, y_pred_dt))

print("\nConfusion Matrix")
print(confusion_matrix(y2_test, y_pred_dt))

# CROSS VALIDATION

dt_cv = cross_val_score(
    best_dt,
    X2,
    y2,
    cv=5,
    scoring='accuracy'
)

print("\nCross Validation Accuracy:",
      dt_cv.mean())



----- DECISION TREE -----
Best Parameters: {'max_depth': 10, 'min_samples_split': 5}
Accuracy: 0.9298245614035088
Precision: 0.9615384615384616
Recall: 0.8928571428571429
F1 Score: 0.9259259259259259

Classification Report
              precision    recall  f1-score   support

           0       0.90      0.97      0.93        29
           1       0.96      0.89      0.93        28

    accuracy                           0.93        57
   macro avg       0.93      0.93      0.93        57
weighted avg       0.93      0.93      0.93        57


Confusion Matrix
[[28  1]
 [ 3 25]]

Cross Validation Accuracy: 0.805325814536341


In [ ]:

# MODEL 2 - GAUSSIAN NAIVE BAYES

print("\n----- GAUSSIAN NAIVE BAYES -----")

gnb = GaussianNB()

gnb.fit(X2_train_scaled, y2_train)

y_pred_gnb = gnb.predict(X2_test_scaled)

print("Accuracy:",
      accuracy_score(y2_test, y_pred_gnb))

print("Precision:",
      precision_score(y2_test, y_pred_gnb))

print("Recall:",
      recall_score(y2_test, y_pred_gnb))

print("F1 Score:",
      f1_score(y2_test, y_pred_gnb))

print("\nClassification Report")
print(classification_report(y2_test, y_pred_gnb))

print("\nConfusion Matrix")
print(confusion_matrix(y2_test, y_pred_gnb))


----- GAUSSIAN NAIVE BAYES -----
Accuracy: 0.8070175438596491
Precision: 0.7575757575757576
Recall: 0.8928571428571429
F1 Score: 0.819672131147541

Classification Report
              precision    recall  f1-score   support

           0       0.88      0.72      0.79        29
           1       0.76      0.89      0.82        28

    accuracy                           0.81        57
   macro avg       0.82      0.81      0.81        57
weighted avg       0.82      0.81      0.81        57


Confusion Matrix
[[21  8]
 [ 3 25]]


In [ ]:
# CROSS VALIDATION

gnb_cv = cross_val_score(
    gnb,
    scaler2.fit_transform(X2),
    y2,
    cv=5,
    scoring='accuracy'
)

print("\nCross Validation Accuracy:",
      gnb_cv.mean())


Cross Validation Accuracy: 0.6860902255639098


In [ ]:
# FINAL MODEL COMPARISON

results = pd.DataFrame({

    'Model': [
        'Random Forest',
        'SVM',
        'Decision Tree',
        'Gaussian NB'
    ],

    'Accuracy': [
        accuracy_score(y1_test, y_pred_rf),
        accuracy_score(y1_test, y_pred_svm),
        accuracy_score(y2_test, y_pred_dt),
        accuracy_score(y2_test, y_pred_gnb)
    ]
})

print("\n===================================")
print("FINAL MODEL COMPARISON")
print("===================================")

print(results)


FINAL MODEL COMPARISON
           Model  Accuracy
0  Random Forest  0.845226
1            SVM  0.850754
2  Decision Tree  0.929825
3    Gaussian NB  0.807018
